# Generated by Django 5.0.3 on 2024-03-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="source",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
