# Generated by Django 5.0.3 on 2024-03-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0002_alter_article_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NegotiationStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="source_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="agneslib.source",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="negotiation_stream_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="agneslib.negotiationstream",
            ),
        ),
    ]
