# Generated by Django 5.0.3 on 2024-03-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agneslib', '0004_alter_article_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agneslib.resource'),
        ),
        migrations.AddField(
            model_name='category',
            name='negotiation_stream_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='agneslib.negotiationstream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agneslib.resource'),
        ),
        migrations.AlterField(
            model_name='category',
            name='source_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agneslib.source'),
        ),
    ]
