# Generated by Django 5.0.3 on 2024-03-11 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agneslib', '0005_article_resource_id_category_negotiation_stream_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='summary',
        ),
    ]
