# Generated by Django 5.0.3 on 2024-03-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agneslib', '0006_remove_resource_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='negotiation_stream_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='resource_id',
        ),
    ]
