# Generated by Django 5.0.3 on 2024-03-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agneslib', '0008_alter_article_category_id_alter_article_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='agneslib.category'),
        ),
    ]
