# Generated by Django 5.0.3 on 2024-03-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agneslib', '0009_alter_article_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
