# Generated by Django 5.0.3 on 2024-03-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agneslib', '0010_article_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='resource_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='agneslib.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='negotiation_stream_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='agneslib.negotiationstream'),
        ),
        migrations.AlterModelTable(
            name='negotiationstream',
            table='NegotiationStream',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='Resource',
        ),
        migrations.AlterModelTable(
            name='source',
            table='Source',
        ),
    ]
