# Generated by Django 5.0.3 on 2024-03-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0011_category_resource_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="resource_id",
        ),
        migrations.AddField(
            model_name="resource",
            name="size",
            field=models.IntegerField(default=1),
        ),
    ]
