# Generated by Django 5.0.3 on 2024-03-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0012_remove_category_resource_id_resource_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="source_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="agneslib.source",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="source_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="linked",
                to="agneslib.source",
            ),
        ),
    ]
