# Generated by Django 5.0.3 on 2024-03-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0013_alter_category_source_id_alter_resource_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
