# Generated by Django 5.0.3 on 2024-03-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0014_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="size",
            field=models.IntegerField(default=1),
        ),
    ]
