# Generated by Django 5.0.3 on 2024-03-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0015_category_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
