# Generated by Django 5.0.3 on 2024-04-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0016_resource_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="size",
        ),
        migrations.RemoveField(
            model_name="category",
            name="size",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="size",
        ),
    ]
