# Generated by Django 4.2.11 on 2024-05-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0018_article_condensed_summary_alter_article_resource_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="condensed_summary",
        ),
    ]
