# Generated by Django 4.2.11 on 2024-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agneslib", "0019_remove_article_condensed_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="crawled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
