import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background">     
      <Providers>
      <div className="dark">
        <div>
          <Image
            src="/climate_action-ai-logo.png"
            alt="Climate Action AI Logo"
            width={350}
            height={50}
            priority
          />
        </div>
      </div>
      <div>{children}</div>
      </Providers>
      </body>
    </html>
  );
}
