import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import NavBar from "./components/NavBar";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container, Row, Col } from "reactstrap";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Climate Action AI",
  description: "Generated by Climate Action AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning data-bs-theme="dark">
      <head>
        <script dangerouslySetInnerHTML={{
          __html: `
            try {
              if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                document.documentElement.classList.add('dark')
              } else {
                document.documentElement.classList.remove('dark')
              }
            } catch (_) {}
          `
        }}/>
      </head>
      <body className="dark"> 
        <Providers>
          <div className="dark">
            <Container>
              <Row>
                <NavBar/>
              </Row>
              <Row>
                <div className="dark">{children}</div>
              </Row>
              </Container>
          </div>
        </Providers>
      </body>
    </html>
  );
}
