import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import NavBar from "./components/NavBar";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container, Row, Col } from "reactstrap";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Climate Action AI",
  description: "Generated by Climate Action AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning data-bs-theme="light">
      <body className="light"> 
        <Providers>
          <div className="bg-img">
            <Image src="/bg.png" alt="Cover Image" quality="100" layout="fill"
              style={{ width: '100%'}}/>
            <Container>
              <Row className="mt-1">
                <NavBar/>
              </Row>
              <Row className="mt-2">
                {children}
              </Row>
            </Container>
          </div>
        </Providers>
      </body>
    </html>
  );
}
